### ISSUE TITLE
Possible new tools to add to the list

### ISSUE THREAD

**Issue by sean-aura** [SethBodine/audit-tools#13]
[Cloudsploit](https://github.com/aquasecurity/cloudsploit)

**Comment by SethBodine** [comment]
https://github.com/spyboy-productions/CloakQuest3r
https://github.com/nemesida-waf/waf-bypass
https://github.com/Moopinger/CLZero

**Comment by SethBodine** [comment]
https://github.com/redhuntlabs/BucketLoot

**Comment by SethBodine** [comment]
> [Cloudsploit](https://github.com/aquasecurity/cloudsploit)
> https://github.com/spyboy-productions/CloakQuest3r https://github.com/nemesida-waf/waf-bypass https://github.com/Moopinger/CLZero
> https://github.com/redhuntlabs/BucketLoot

Will review these tools soon.
