### ISSUE TITLE
go-lang apps are not being built at container launch

### ISSUE THREAD

**Issue by sean-aura** [SethBodine/audit-tools#14]
**Describe the bug**
go-lang build steps in updatetools script do not execute

**To Reproduce**
1. Launch Container
2. Allow updatetools script to complete
3. Try and run go-lang apps

**Expected behavior**
Go-lang apps should build

**Comment by SethBodine** [comment]
Fixed in [6753359a8aaf85ed48c5b7ec197b71ef2a22f068](https://github.com/SethBodine/audit-tools/commit/6753359a8aaf85ed48c5b7ec197b71ef2a22f068)
